"""
Turn results/*.json (produced by the real runs) into LaTeX tables/figures the
paper \\input's. This keeps the paper honest: every number is generated from a
run, never hand-typed. If a results file is missing, it emits a visible TODO so
an unfilled number can never masquerade as a result.
"""
from __future__ import annotations
import os, sys, json

RES = sys.argv[1] if len(sys.argv) > 1 else "results"
OUT = sys.argv[2] if len(sys.argv) > 2 else "research_paper/generated_results.tex"


def load(name):
    p = os.path.join(RES, name)
    return json.load(open(p)) if os.path.exists(p) else None


def todo(what):
    return "\\textbf{\\textcolor{red}{[TODO: run %s]}}" % what


def longrange_table(data):
    if not data:
        return "%% longrange\n\\newcommand{\\longrangeTable}{" + todo("eval\\_longrange") + "}\n"
    rows = data["rows"]
    lengths = sorted({r["seq_len"] for r in rows})
    def acc(model, L):
        for r in rows:
            if r["model"] == model and r["seq_len"] == L:
                return f"{100*r['query_acc']:.1f}"
        return "--"
    body = ""
    for L in lengths:
        body += f"{L} & {acc('ssm', L)} & {acc('mnemosyne', L)} \\\\\n"
    tbl = ("\\begin{tabular}{lcc}\\toprule\n"
           "Seq.\\ length & SSM (no mem.) & Mnemosyne \\\\\\midrule\n"
           + body + "\\bottomrule\\end{tabular}")
    return "\\newcommand{\\longrangeTable}{%\n" + tbl + "}\n"


def pretrain_macros(data):
    if not data:
        return ("\\newcommand{\\ssmLoss}{" + todo("train\\_mae") + "}\n"
                "\\newcommand{\\mnemLoss}{" + todo("train\\_mae") + "}\n"
                "\\newcommand{\\mnemGate}{" + todo("train\\_mae") + "}\n")
    sl = data["ssm"]["log"][-1]["loss"]
    ml = data["mnemosyne"]["log"][-1]["loss"]
    mg = data["mnemosyne"]["log"][-1].get("gate")
    return (f"\\newcommand{{\\ssmLoss}}{{{sl}}}\n"
            f"\\newcommand{{\\mnemLoss}}{{{ml}}}\n"
            f"\\newcommand{{\\mnemGate}}{{{mg}}}\n")


def gue_table(data):
    if not data:
        return "\\newcommand{\\gueTable}{" + todo("eval\\_gue") + "}\n"
    body = ""
    for task, d in data.items():
        s = d.get("ssm", {}); m = d.get("mnemosyne", {})
        if not s:
            continue
        body += (f"{task.replace('_',' ')} & {s['mcc']:.3f} & {m['mcc']:.3f} & "
                 f"{m['mcc']-s['mcc']:+.3f} \\\\\n")
    tbl = ("\\begin{tabular}{lccc}\\toprule\n"
           "Task & SSM (MCC) & Mnemosyne (MCC) & $\\Delta$ \\\\\\midrule\n"
           + body + "\\bottomrule\\end{tabular}")
    return "\\newcommand{\\gueTable}{%\n" + tbl + "}\n"


def main():
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    parts = ["% AUTO-GENERATED by src/make_report.py -- do not edit by hand\n"]
    parts.append(longrange_table(load("longrange.json")))
    parts.append(pretrain_macros(load("pretrain/pretrain_log.json")))
    parts.append(gue_table(load("gue.json")))
    open(OUT, "w").write("\n".join(parts))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
